### ISSUE TITLE
Problems found with Linux at runtime

### ISSUE THREAD

**Issue by Nianmou** [a2x/cs2-dumper#266]
warning: multiple variants are never constructed
  --> src/source2/schema_system/schema_type.rs:7:5
   |
6  | pub enum SchemaAtomicCategory {
   |          -------------------- variants in this enum
7  |     Basic = 0,
   |     ^^^^^
8  |     T,
   |     ^
9  |     CollectionOfT,
   |     ^^^^^^^^^^^^^
10 |     TF,
   |     ^^
11 |     TT,
   |     ^^
12 |     TTF,
   |     ^^^
13 |     I,
   |     ^
14 |     None,
   |     ^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: multiple variants are never constructed
  --> src/source2/schema_system/schema_type.rs:19:5
   |
18 | pub enum SchemaTypeCategory {
   |          ------------------ variants in this enum
19 |     BuiltIn = 0,
   |     ^^^^^^^
20 |     Ptr,
   |     ^^^
21 |     Bitfield,
   |     ^^^^^^^^
22 |     FixedArray,
   |     ^^^^^^^^^^
23 |     Atomic,
   |     ^^^^^^
24 |     DeclaredClass,
   |     ^^^^^^^^^^^^^
25 |     DeclaredEnum,
   |     ^^^^^^^^^^^^
26 |     None,
   |     ^^^^

warning: multiple fields are never read
  --> src/source2/schema_system/schema_type.rs:88:9
   |
87 | pub union SchemaTypeUnion {
   |           --------------- fields in this union
88 |     pub schema_type: Pointer64<SchemaType>,
   |         ^^^^^^^^^^^
89 |     pub class_binding: Pointer64<SchemaClassBinding>,
   |         ^^^^^^^^^^^^^
90 |     pub enum_binding: Pointer64<SchemaEnumBinding>,
   |         ^^^^^^^^^^^^
91 |     pub array: SchemaArrayT,
   |         ^^^^^
92 |     pub atomic: SchemaAtomicT,
   |         ^^^^^^
93 |     pub atomic_tt: SchemaAtomicTT,
   |         ^^^^^^^^^
94 |     pub atomic_tf: SchemaAtomicTF,
   |         ^^^^^^^^^
95 |     pub atomic_ttf: SchemaAtomicTTF,
   |         ^^^^^^^^^^
96 |     pub atomic_i: SchemaAtomicI,
   |         ^^^^^^^^

warning: variants `None`, `Fast`, and `Slow` are never constructed
 --> src/source2/tier1/utl_memory_pool.rs:5:5
  |
4 | pub enum MemoryPoolGrowType {
  |          ------------------ variants in this enum
5 |     None = 0,
  |     ^^^^
6 |     Fast,
  |     ^^^^
7 |     Slow,
  |     ^^^^

warning: method `block_size` is never used
  --> src/source2/tier1/utl_ts_hash.rs:53:12
   |
42 | / impl<D, const C: usize, K> UtlTsHash<D, C, K>
43 | | where
44 | |     D: Pod + PointerExt,
45 | |     K: Pod,
   | |___________- method in this implementation
...
53 |       pub fn block_size(&self) -> i32 {
   |              ^^^^^^^^^^

warning: `cs2-dumper` (bin "cs2-dumper" test) generated 5 warnings
    Finished `test` profile [optimized + debuginfo] target(s) in 4m 52s
     Running unittests src/main.rs (target/debug/deps/cs2_dumper-b23d66e86ce730ec)

running 5 tests
Error: Memflow(Error(OsLayer, ModuleNotFound))
test analysis::offsets::tests::global_vars ... FAILED
thread 'analysis::offsets::tests::build_number' panicked at src/analysis/offsets.rs:147:73:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test analysis::offsets::tests::build_number ... FAILED
Error: Memflow(Error(OsLayer, ModuleNotFound))
test analysis::offsets::tests::local_player_controller ... FAILED
Error: Memflow(Error(OsLayer, ModuleNotFound))
test analysis::offsets::tests::local_player_pawn ... FAILED
thread 'analysis::offsets::tests::window_size' panicked at src/analysis/offsets.rs:251:86:
called `Option::unwrap()` on a `None` value
test analysis::offsets::tests::window_size ... FAILED

failures:

failures:
    analysis::offsets::tests::build_number
    analysis::offsets::tests::global_vars
    analysis::offsets::tests::local_player_controller
    analysis::offsets::tests::local_player_pawn
    analysis::offsets::tests::window_size

test result: FAILED. 0 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s

error: test failed, to rerun pass `--bin cs2-dumper`

**Comment by Nianmou** [comment]
`root@ECS8468:/mnt/steam/cs2/cs2-dumper# cargo test -- --nocapture
warning: multiple variants are never constructed
  --> src/source2/schema_system/schema_type.rs:7:5
   |
6  | pub enum SchemaAtomicCategory {
   |          -------------------- variants in this enum
7  |     Basic = 0,
   |     ^^^^^
8  |     T,
   |     ^
9  |     CollectionOfT,
   |     ^^^^^^^^^^^^^
10 |     TF,
   |     ^^
11 |     TT,
   |     ^^
12 |     TTF,
   |     ^^^
13 |     I,
   |     ^
14 |     None,
   |     ^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: multiple variants are never constructed
  --> src/source2/schema_system/schema_type.rs:19:5
   |
18 | pub enum SchemaTypeCategory {
   |          ------------------ variants in this enum
19 |     BuiltIn = 0,
   |     ^^^^^^^
20 |     Ptr,
   |     ^^^
21 |     Bitfield,
   |     ^^^^^^^^
22 |     FixedArray,
   |     ^^^^^^^^^^
23 |     Atomic,
   |     ^^^^^^
24 |     DeclaredClass,
   |     ^^^^^^^^^^^^^
25 |     DeclaredEnum,
   |     ^^^^^^^^^^^^
26 |     None,
   |     ^^^^

warning: multiple fields are never read
  --> src/source2/schema_system/schema_type.rs:88:9
   |
87 | pub union SchemaTypeUnion {
   |           --------------- fields in this union
88 |     pub schema_type: Pointer64<SchemaType>,
   |         ^^^^^^^^^^^
89 |     pub class_binding: Pointer64<SchemaClassBinding>,
   |         ^^^^^^^^^^^^^
90 |     pub enum_binding: Pointer64<SchemaEnumBinding>,
   |         ^^^^^^^^^^^^
91 |     pub array: SchemaArrayT,
   |         ^^^^^
92 |     pub atomic: SchemaAtomicT,
   |         ^^^^^^
93 |     pub atomic_tt: SchemaAtomicTT,
   |         ^^^^^^^^^
94 |     pub atomic_tf: SchemaAtomicTF,
   |         ^^^^^^^^^
95 |     pub atomic_ttf: SchemaAtomicTTF,
   |         ^^^^^^^^^^
96 |     pub atomic_i: SchemaAtomicI,
   |         ^^^^^^^^

warning: variants `None`, `Fast`, and `Slow` are never constructed
 --> src/source2/tier1/utl_memory_pool.rs:5:5
  |
4 | pub enum MemoryPoolGrowType {
  |          ------------------ variants in this enum
5 |     None = 0,
  |     ^^^^
6 |     Fast,
  |     ^^^^
7 |     Slow,
  |     ^^^^

warning: method `block_size` is never used
  --> src/source2/tier1/utl_ts_hash.rs:53:12
   |
42 | / impl<D, const C: usize, K> UtlTsHash<D, C, K>
43 | | where
44 | |     D: Pod + PointerExt,
45 | |     K: Pod,
   | |___________- method in this implementation
...
53 |       pub fn block_size(&self) -> i32 {
   |              ^^^^^^^^^^

warning: `cs2-dumper` (bin "cs2-dumper" test) generated 5 warnings
    Finished `test` profile [optimized + debuginfo] target(s) in 0.25s
     Running unittests src/main.rs (target/debug/deps/cs2_dumper-b23d66e86ce730ec)

running 5 tests
Error: Memflow(Error(OsLayer, ModuleNotFound))
test analysis::offsets::tests::global_vars ... FAILED
thread 'analysis::offsets::tests::build_number' panicked at src/analysis/offsets.rs:147:73:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test analysis::offsets::tests::build_number ... FAILED
Error: Memflow(Error(OsLayer, ModuleNotFound))
Error: Memflow(Error(OsLayer, ModuleNotFound))
test analysis::offsets::tests::local_player_controller ... FAILED
test analysis::offsets::tests::local_player_pawn ... FAILED
thread 'analysis::offsets::tests::window_size' panicked at src/analysis/offsets.rs:251:86:
called `Option::unwrap()` on a `None` value
test analysis::offsets::tests::window_size ... FAILED

failures:

failures:
    analysis::offsets::tests::build_number
    analysis::offsets::tests::global_vars
    analysis::offsets::tests::local_player_controller
    analysis::offsets::tests::local_player_pawn
    analysis::offsets::tests::window_size

test result: FAILED. 0 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s

error: test failed, to rerun pass `--bin cs2-dumper``

**Comment by Nianmou** [comment]
Used curl --proto '=https' --tlsv1.2 -sSf https://sh.memflow.io | bash but it's still like this

**Comment by Nianmou** [comment]
root@ECS8468:/mnt/steam/cs2/cs2-dumper# memflowup --version
memflowup 0.2.0

**Comment by a2x** [comment]
The linux branch is outdated and it's not something that I can fix right now. A PR would be great if someone wants to do it.

**Comment by daniliammo** [comment]
> The linux branch is outdated and it's not something that I can fix right now. A PR would be great if someone wants to do it.

@a2x 
I want to update Linux branch. Tell Me how to do it please.

**Comment by Nianmou** [comment]
> > Linux分支已经过时了，我现在无法修复。如果有人愿意修复，最好发个PR。
> 
> @a2x 我想更新 Linux 分支。请告诉我该怎么做。@a2x我想更新 Linux 分支。请告诉我该怎么做。

Do you know how to fix this, I think he's important to me, I also need the linux offset
